_("DSLR Imaging with Mount Control");
_("Canon EOS 350D, Goto mount");
_("&Object name");
_("Object Position");
_("DF Cyg");
_("RA");
_("=");
_("12 : 44 : 55.657");
_("Decl");
_("=");
_("+36 : 46 : 44.67 ");
_("&Number of frames");
_("&Duration (sec)");
_("Exposure");
_("(none)");
_("Observations plan file");
_("&Move");
_("&Shoot");
_("&Abort");
_("A&uto");
_("S&kip");
_("E&xit");
_("StatusBar");
_("RA 12:34.5 D +12:34");
_("VAuto");
_("DSLR Imaging with Mount Control");
_("Canon EOS 350D, Goto mount");
_("Came&ra Type");
_("Canon EOS 350D");
_("&Com port");
_("COM1");
_("COM2");
_("COM3");
_("COM4");
_("&Mirror lockup");
_("Delay before &lockup");
_("Delay before &frame");
_("Camera Shutter setup");
_("Mount &Type");
_("Goto mount");
_("LX-200 mount");
_("C&om port");
_("COM1");
_("COM2");
_("COM3");
_("COM4");
_("Mount setup");
_("&Save");
_("Cancel");
_("VAuto options");
_("DSLR Imaging with Mount Control");
_("Canon EOS 350D, Goto mount");
_("VAuto, version 1.2\nCopyright (c) KVI, 2009-2012.");
_("Supported camera types: Canon EOS\nSupported mount types: NexStar, LX-200");
_("Close");
_("About VAuto");
_("&Object name");
_("&Number of frames");
_("&Duration (sec)");
_("Manual exposure control");
_("Observations plan file");
_("(none)");
_("&Start");
_("&Abort");
_("E&xit");
_("StatusBar");
_("Control");
_("Came&ra Type");
_("Canon EOS 350D");
_("&Com port");
_("COM1");
_("COM2");
_("COM3");
_("COM4");
_("&Mirror lockup");
_("Delay after &lockup");
_("Delay after &frame");
_("Camera Shutter setup");
_("Camera");
_("Mount &Type");
_("Goto mount");
_("LX-200 mount");
_("C&om port");
_("COM1");
_("COM2");
_("COM3");
_("COM4");
_("Mount setup");
_("Mount");
_("Station");
_("Options");
_("Options");
_("DSLR Imaging with Mount Control");
_("Canon EOS 350D, Goto mount");
_("VAuto");
_("&Debug log window");
_("Observation &Log Folder");
_("VAuto");
_("Came&ra Type");
_("Canon EOS 350D");
_("&Com port");
_("COM1");
_("COM2");
_("COM3");
_("COM4");
_("&Mirror lockup");
_("Delay after &lockup");
_("Delay after &frame");
_("&ISO speed");
_("100");
_("200");
_("400");
_("800");
_("1600");
_("3200");
_("&Battery alert level");
_("Camera Shutter setup");
_("Camera");
_("Mount &Type");
_("Goto mount");
_("LX-200 mount");
_("C&om port");
_("COM1");
_("COM2");
_("COM3");
_("COM4");
_("Mount setup");
_("Mount");
_("&Longitude");
_("Latitu&de");
_("Station");
_("Station");
_("&Save");
_("Cancel");
_("Options");
